add mysql configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -115,9 +115,16 @@ if [ $? -eq 1  ];then
 	echo -e "\033[41;34m apache install failed.\033[0m"
 	exit 1
 fi
+sh auto/mysql/mysql
+if [ $? -eq 1  ];then
+	echo -e "\033[41;34m mysql install failed.\033[0m"
+	exit 1
+fi
+
 sh auto/php/php
 if [ $? -eq 1  ];then
 	echo -e "\033[41;34m php install failed.\033[0m"
+	exit 1
 fi
 
 
