update files

diff --git a/auto/package b/auto/package
--- a/auto/package
+++ b/auto/package
@@ -6,9 +6,53 @@ fi
 ##########################################################
 #check package
 checkForYum(){
-	for elem in ${PACKAGE[@]}; do
-		echo $elem
+	error=0
+	for el in ${PACKAGE[@]}; do
+		if [ ${#el} -eq 0 ];then
+			continue
+		else
+			elem=$el
+		fi
+		${AUTOINSTALL_COMMOND} info installed | grep "${elem}" | grep -v grep >/dev/null 2>&1		
+		if [ $? -eq 0 ];then
+			echo "The $elem has been installed."
+		else
+			${AUTOINSTALL_COMMOND} -y install $elem 
+			if [ $? -ne 0 ];then
+				error=$(($error + 1))
+				echo -e "\033[41;34mThe $elem install failed.\033[0m"
+			fi
+		fi
 	done
+	if [ $error -gt 0 ];then
+		echo "Install the dependent packages before proceeding."
+		exit 1
+	fi
+}
+#download source
+function downloadPackage(){
+	err=0
+	dirs=$(ls -F ${AUTOINSTALL_SOURCES} | grep "/$")
+	for el in $dirs;do	
+		rm -rf ${AUTOINSTALL_SOURCES}/$el > /dev/null 2>&1
+	done
+	for source in ${SOURCEURL[@]};do
+		filename=$(find ${AUTOINSTALL_SOURCES} -type f -name ${source##*/})	
+		if [ ${#filename} -gt 0 ];then
+			echo -e "\033[42;30m${source##*/}already exists.\033[0m"
+			continue
+		fi
+		wget -P ${AUTOINSTALL_SOURCES} $source
+		if [ $? -ne 0 ];then
+			echo -e "\033[41;34mThe ${source##*/} download failed.\033[0m"
+			err=$(($err + 1))
+		fi
+	done
+	if [ $err -gt 0 ];then
+		echo "Install the dependent packages before proceeding."
+		exit 1
+	fi
+		
 }
 
 case ${AUTOINSTALL_COMMOND} in
@@ -27,5 +71,5 @@ case ${AUTOINSTALL_COMMOND} in
 	;;
 esac
 
-
+downloadPackage
 
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,7 +12,7 @@ length=$(expr length ${AUTOINSTALL_COMMOND})
 TEMPFILE=$(mktemp)
 ${AUTOINSTALL_COMMOND}  update > ${TEMPFILE} 2>/dev/null
 if [ $? -ne 0 ];then
-	echo -e "\033[42;30mthe ${AUTOINSTALL_COMMOND} update failed,please update manually.\033[0m"
+	echo -e "\033[41;34mthe ${AUTOINSTALL_COMMOND} update failed,please update manually.\033[0m"
 	while read line;do
 		echo -e "$line"
 	done < ${TEMPFILE}
@@ -53,15 +53,18 @@ while read line; do
 
 	fi
 done < source.ini
-url=($item_url)
+SOURCEURL=($item_url)
 #endee
 commond_wget=$(which wget)
 [ "${commond_wget:0-4}" == "wget" ] || (${AUTOINSTALL_COMMOND} -y install wget >/dev/null 2&1)
 if [ $? -ne 0 ];then
-	echo -e "\033[42;30mPlease install wget\033[0m"
+	echo -e "\033[41;34mPlease install wget\033[0m"
 	exit 1
 fi
-
-
-
+commond_grep=$(which grep)
+[ "${commond_grep:0-4}" == "grep" ] || (${AUTOINSTALL_COMMOND} -y install grep >/dev/null 2&1)
+if [ $? -ne 0 ];then
+	echo -e "\033[41;34mPlease install grep\033[0m"
+	exit 1
+fi
 . auto/package
